batch_size: 300
epochs: 15
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BioScan-CLIP_0_1_2
using_train_seen_for_pre_train: true
unfreeze_all_para: false
open_clip_ver: true
bin_for_positive_and_negative_pairs: true

image:
  input_type: image
  model: lora_vit
dna:
  input_type: sequence
  model: lora_barcode_bert
language:
  input_type: sequence
  model: lora_bert


model_output_name: lora_vit_lora_barcode_bert_lora_bert_ssl_batch_size_400_with_all_gather
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/version_0_1_1/lora_vit_lora_barcode_bert_lora_bert_ssl_batch_size_400/best.pth
insect_ckpt_path: ${project_root_path}/ckpt/bioscan_clip/lora_vit_lora_barcode_bert_lora_bert_ssl_batch_size_400_INSECT/best.pth
output_dim: 768
port: 12318

fine_tuning_set:
  batch_size: 72
  epochs: 15
  fine_tune_model_output_dir: ${model_output_dir}/${model_config.model_output_name}/supervise_fine_tune_ckpt

loss_setup:
  local_loss: false
  gather_with_grad: false
  use_horovod: false
