batch_size: 400
epochs: 15
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BioScan-CLIP_without_train_seen
using_train_seen_for_pre_train: false

image:
  input_type: image
  model: lora_vit
language:
  input_type: sequence
  model: lora_bert

bioscan_bert_checkpoint: ${project_root_path}/ckpt/BarcodeBERT/5_mer/model_41.pth
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/version_0_1_0/lora_vit_lora_bert_ssl_batch_size_400/best.pth
model_output_dir: ${project_root_path}/ckpt/bioscan_clip
model_output_name: lora_vit_lora_bert_ssl_batch_size_400_without_train_seen
evaluation_period: 1
output_dim: 768
port: 12317