batch_size: 900
epochs: 15
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BioScan-CLIP
image_input_type: image
image_model: lora_vit
dna_input_type: feature
model_output_dir: ${project_root_path}/ckpt/bioscan_clip/
model_output_name: lora_vit_ssl_old_aug_batch_size_900
evaluation_period: 1
ckpt_path: ${model_config.model_output_dir}/${model_config.model_output_name}/last.pth
new_transform: false