batch_size: 16384
epochs: 1
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BioScan-CLIP
image:
  input_type: feature
  input_dim: 512
  hidden_dim: 768
dna:
  input_type: feature
  freeze: true
model_output_dir: ${project_root_path}/ckpt/bioscan_clip/
model_output_name: mlp_ssl_batch_size_16384_barcode_bert_freeze
evaluation_period: 10
ckpt_path: ${model_config.model_output_dir}/${model_config.model_output_name}/last.pth
output_dim: 768