batch_size: 800
epochs: 10
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BioScan-CLIP
image:
  image_input_type: image
  image_model: vit_with_mlp_adapter
  input_dim: 512
  hidden_dim: 768
  output_dim: 768
dna:
  dna_input_type: sequence
  dna_model: barcode_bert_with_mlp_adapter
  input_dim: 768
  hidden_dim: 768
  output_dim: 768
model_output_dir: ${project_root_path}/ckpt/bioscan_clip/
model_output_name: lora_vit_barcode_bert_freeze_ssl
evaluation_period: 1
ckpt_path: ${model_config.model_output_dir}/${model_config.model_output_name}/last.pth
new_transform: true
input_dim: 512
hidden_dim: 512
output_dim: 768