batch_size: 500
epochs: 10
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BioScan-CLIP

image:
  input_type: image
  model: lora_vit
dna:
  input_type: feature
  freeze: true


model_output_dir: ${project_root_path}/ckpt/bioscan_clip/
model_output_name: lora_vit_lora_barcode_bert_ssl_batch_size_400
evaluation_period: 1
ckpt_path: ${model_config.model_output_dir}/${model_config.model_output_name}/last.pth
output_dim: 768
port: 12315