batch_size: 400
epochs: 5
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BioScan-CLIP

image:
  input_type: image
  model: lora_vit
dna:
  input_type: feature
  freeze: true
language:
  input_type: sequence
  model: lora_bert

bioscan_bert_checkpoint: ${project_root_path}/ckpt/BarcodeBERT/5_mer/model_41.pth
model_output_dir: ${project_root_path}/ckpt/bioscan_clip/
model_output_name: lora_vit_freeze_barcode_bert_lora_bert_ssl_batch_size_400
evaluation_period: 1
ckpt_path: ${model_config.model_output_dir}/${model_config.model_output_name}/last.pth
output_dim: 768
port: 12316